### ISSUE TITLE
Crash when trying to use Uncrafting table

### ISSUE THREAD

**Issue by lospejos** [PTOM76/UncraftingTable#4]
Crash when trying to use Uncrafting table

`Minecraft 1.19.2` with `fabric-api-0.64.0+1.19.2`, `Fabric loader 0.14.10` and `UncraftingTable-fabric-1.1.1`:

Uncrafting table successfully created, when trying to use (right click), crash occur:

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-11-02 20:15:55
Description: Rendering screen

java.lang.AbstractMethodError: Receiver class ml.pkom.uncraftingtable.UncraftingScreen does not define or inherit an implementation of the resolved method 'abstract void method_2389(net.minecraft.class_4587, float, int, int)' of abstract class net.minecraft.class_465.
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:100)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:881)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by PTOM76** [comment]
What is the version of MCPitanLibarch?

**Comment by lospejos** [comment]
Checked `MCPitanLibarch`, it's version was not the recent.
With the recent `mcpitanlibarch-1.1.0-1.19-fabric` the mod `UncraftingTable-fabric-1.1.1` works without crashes.

Thanks, I'm closing the issue.
